// SPDX-License-Identifier: Apache-2.0
//! Helpers shared by the test modules ported from batch 1 onward: the reference's voucher
//! evidence label, the tag -> ledger lookup the module invariants resolve figures through, and
//! checked counts and sums.

use std::collections::HashMap;

use crate::book::{Book, Voucher};
use crate::error::{AuditError, Result};
use crate::findings::Value;
use crate::ledger_ids::stable_ledger_tag;
use crate::read::iso;
use crate::text_tables;

/// The last 12 characters of a GUID, as the reference's `guid[-12:]` takes them: characters, not
/// bytes, so a non-ASCII GUID neither panics nor gives a different label.
pub(crate) fn guid_tail12(guid: &str) -> &str {
    let chars = guid.chars().count();
    let cut = guid
        .char_indices()
        .nth(chars.saturating_sub(12))
        .map_or(guid.len(), |(i, _)| i);
    &guid[cut..]
}

/// The reference's voucher evidence label: `"<type> <number> on <date>"`, with the GUID's last 12
/// characters standing in for a missing number.
pub(crate) fn voucher_label(v: &Voucher) -> String {
    let num = if v.number.is_empty() {
        guid_tail12(&v.guid)
    } else {
        v.number.as_str()
    };
    format!("{} {} on {}", v.vtype, num, iso(&v.date))
}

/// Every ledger by its stable tag, for resolving a `<figure>_<tag>` id back to its ledger. If two
/// ledgers ever shared a tag, this keeps the last in name order, where the reference's dict keeps
/// the last in read order -- not reachable while tags are unique.
pub(crate) fn ledgers_by_tag(book: &Book) -> Result<HashMap<String, &String>> {
    let mut out = HashMap::new();
    for name in book.ledgers.keys() {
        out.insert(stable_ledger_tag(book, name)?, name);
    }
    Ok(out)
}

/// The error every checked total in a test module raises on i64 overflow.
pub(crate) fn overflow(test_id: &str) -> AuditError {
    AuditError::Config(format!("{test_id}: a total overflowed i64 paise"))
}

/// A count as a figure value.
pub(crate) fn count(test_id: &str, n: usize) -> Result<Value> {
    Ok(Value::Int(i64::try_from(n).map_err(|_| overflow(test_id))?))
}

// The reference's case mapping is Python 3.13's (`unicodedata.unidata_version` 15.1.0); see
// `docs/tax-audit/parity-spec-v1.md`. The two lists below were generated by
// `parity/case_exceptions.py` against the Unicode tables of the pinned toolchain (17.0.0); a
// toolchain with other tables fails `the_case_tables_are_the_ones_the_exceptions_were_generated_for`
// until they are regenerated.

/// Code points whose `to_uppercase` under the pinned toolchain's tables differs from Python 3.13's
/// `str.upper()`; Python maps every one of them to itself.
const UPPER_UNCHANGED: [u32; 55] = [
    0x019B, 0x0264, 0x1C8A, 0xA7CD, 0xA7CF, 0xA7D3, 0xA7D5, 0xA7DB, 0x10D70, 0x10D71, 0x10D72,
    0x10D73, 0x10D74, 0x10D75, 0x10D76, 0x10D77, 0x10D78, 0x10D79, 0x10D7A, 0x10D7B, 0x10D7C,
    0x10D7D, 0x10D7E, 0x10D7F, 0x10D80, 0x10D81, 0x10D82, 0x10D83, 0x10D84, 0x10D85, 0x16EBB,
    0x16EBC, 0x16EBD, 0x16EBE, 0x16EBF, 0x16EC0, 0x16EC1, 0x16EC2, 0x16EC3, 0x16EC4, 0x16EC5,
    0x16EC6, 0x16EC7, 0x16EC8, 0x16EC9, 0x16ECA, 0x16ECB, 0x16ECC, 0x16ECD, 0x16ECE, 0x16ECF,
    0x16ED0, 0x16ED1, 0x16ED2, 0x16ED3,
];

/// The same for `to_lowercase` against `str.lower()`.
const LOWER_UNCHANGED: [u32; 55] = [
    0x1C89, 0xA7CB, 0xA7CC, 0xA7CE, 0xA7D2, 0xA7D4, 0xA7DA, 0xA7DC, 0x10D50, 0x10D51, 0x10D52,
    0x10D53, 0x10D54, 0x10D55, 0x10D56, 0x10D57, 0x10D58, 0x10D59, 0x10D5A, 0x10D5B, 0x10D5C,
    0x10D5D, 0x10D5E, 0x10D5F, 0x10D60, 0x10D61, 0x10D62, 0x10D63, 0x10D64, 0x10D65, 0x16EA0,
    0x16EA1, 0x16EA2, 0x16EA3, 0x16EA4, 0x16EA5, 0x16EA6, 0x16EA7, 0x16EA8, 0x16EA9, 0x16EAA,
    0x16EAB, 0x16EAC, 0x16EAD, 0x16EAE, 0x16EAF, 0x16EB0, 0x16EB1, 0x16EB2, 0x16EB3, 0x16EB4,
    0x16EB5, 0x16EB6, 0x16EB7, 0x16EB8,
];

/// Python 3.13's `str.isspace()` for one character: Rust's `char::is_whitespace` plus
/// U+001C..=U+001F, which Python counts as whitespace and Rust does not (measured over every code
/// point: the only difference).
pub(crate) fn py_isspace(c: char) -> bool {
    c.is_whitespace() || ('\u{1c}'..='\u{1f}').contains(&c)
}

/// Python 3.13's `str.strip()` with no argument.
pub(crate) fn py_strip(text: &str) -> &str {
    text.trim_matches(py_isspace)
}

/// Python 3.13's `str.upper()`: full Unicode case mapping, pinned to Unicode 15.1.0.
pub(crate) fn py_upper(text: &str) -> String {
    text.chars()
        .flat_map(|c| {
            let keep = UPPER_UNCHANGED.binary_search(&u32::from(c)).is_ok();
            let mapped: Vec<char> = if keep {
                vec![c]
            } else {
                c.to_uppercase().collect()
            };
            mapped
        })
        .collect()
}

/// Python 3.13's `str.lower()`: full lower-case mapping pinned per code point, and the final-sigma
/// rule as CPython applies it (a capital sigma lowers to U+03C2 when the nearest non-case-ignorable
/// character before it is cased and the nearest after it is not), on Python's own Cased and
/// Case_Ignorable sets (`text_tables`, generated by `parity/text_semantics.py`). Replayed against
/// Python on the acceptance set by `text_probe_tests` below.
pub(crate) fn py_lower(text: &str) -> String {
    let chars: Vec<char> = text.chars().collect();
    let mut out = String::with_capacity(text.len());
    for (i, &c) in chars.iter().enumerate() {
        if c == '\u{3a3}' {
            out.push(if final_sigma(&chars, i) {
                '\u{3c2}'
            } else {
                '\u{3c3}'
            });
        } else if LOWER_UNCHANGED.binary_search(&u32::from(c)).is_ok() {
            out.push(c);
        } else {
            out.extend(c.to_lowercase());
        }
    }
    out
}

fn in_ranges(table: &[(u32, u32)], c: char) -> bool {
    let cp = u32::from(c);
    table
        .binary_search_by(|&(lo, hi)| {
            if hi < cp {
                std::cmp::Ordering::Less
            } else if lo > cp {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// CPython's `handle_capital_sigma` on Python's own tables.
fn final_sigma(chars: &[char], i: usize) -> bool {
    let ignorable = |c: char| in_ranges(&text_tables::PY_CASE_IGNORABLE, c);
    let cased = |c: char| in_ranges(&text_tables::PY_CASED, c);
    let before = chars[..i].iter().rev().find(|&&c| !ignorable(c));
    if !before.is_some_and(|&c| cased(c)) {
        return false;
    }
    let after = chars[i + 1..].iter().find(|&&c| !ignorable(c));
    !after.is_some_and(|&c| cased(c))
}

/// Python 3.13's `str.isalnum()` for one character: Rust's `is_alphanumeric` without the ranges
/// Python does not count (measured to be the only difference, and one-way).
pub(crate) fn py_isalnum(c: char) -> bool {
    c.is_alphanumeric() && !in_ranges(&text_tables::NOT_PY_ALNUM, c)
}

/// Python's `\w` in a `str` pattern: `isalnum()` or an underscore.
pub(crate) fn py_is_word(c: char) -> bool {
    c == '_' || py_isalnum(c)
}

/// Python 3.13's `str.split()` with no argument: split on runs of Python whitespace, dropping empty
/// pieces.
#[cfg_attr(not(test), allow(dead_code))] // first caller: the batch-2 ports
pub(crate) fn py_split(text: &str) -> Vec<&str> {
    text.split(py_isspace).filter(|p| !p.is_empty()).collect()
}

/// One element of a literal regular expression in the reference: an ASCII character (matched as
/// Python's `re.I` matches it), `\s?`, or `\b`.
#[derive(Clone, Copy)]
pub(crate) enum ReTok {
    Lit(char),
    OptSpace,
    Boundary,
}

/// Whether `c` matches the ASCII pattern character `p` under Python's `re.I`: its own two cases,
/// plus the few non-ASCII characters `re.I` folds onto a letter (`text_tables::PY_CI_EXTRA`).
fn py_ci_eq(c: char, p: char) -> bool {
    if c.eq_ignore_ascii_case(&p) {
        return true;
    }
    let up = p.to_ascii_uppercase();
    text_tables::PY_CI_EXTRA
        .iter()
        .any(|(l, cps)| *l == up && cps.contains(&u32::from(c)))
}

fn matches_at(chars: &[char], at: usize, toks: &[ReTok]) -> bool {
    let Some((tok, rest)) = toks.split_first() else {
        return true;
    };
    match tok {
        ReTok::Lit(p) => {
            chars.get(at).is_some_and(|&c| py_ci_eq(c, *p)) && matches_at(chars, at + 1, rest)
        }
        ReTok::OptSpace => {
            (chars.get(at).is_some_and(|&c| py_isspace(c)) && matches_at(chars, at + 1, rest))
                || matches_at(chars, at, rest)
        }
        ReTok::Boundary => {
            let before = at > 0 && py_is_word(chars[at - 1]);
            let after = chars.get(at).is_some_and(|&c| py_is_word(c));
            before != after && matches_at(chars, at, rest)
        }
    }
}

/// Parse the subset of Python regular-expression syntax the reference's literal patterns use:
/// alternatives joined by `|`, each a run of ASCII letters and digits, `\b` and `\s?`. Anything
/// else is refused (a pattern outside the subset needs its own matcher, not a silent guess).
pub(crate) fn re_alternatives(pattern: &str) -> Vec<Vec<ReTok>> {
    pattern
        .split('|')
        .map(|alt| {
            let mut toks = Vec::new();
            let mut it = alt.chars().peekable();
            while let Some(c) = it.next() {
                match c {
                    '\\' => match (it.next(), it.peek()) {
                        (Some('b'), _) => toks.push(ReTok::Boundary),
                        (Some('s'), Some('?')) => {
                            it.next();
                            toks.push(ReTok::OptSpace);
                        }
                        other => panic!("unsupported escape {other:?} in {pattern:?}"),
                    },
                    c if c.is_ascii_alphanumeric() || c == ' ' => toks.push(ReTok::Lit(c)),
                    c => panic!("unsupported character {c:?} in {pattern:?}"),
                }
            }
            toks
        })
        .collect()
}

/// `re.search(alternatives, text, re.I)` for a reference regular expression made only of ASCII
/// literals, `\s?` and `\b`, joined by `|`.
pub(crate) fn py_re_search(text: &str, alternatives: &[&[ReTok]]) -> bool {
    let chars: Vec<char> = text.chars().collect();
    (0..=chars.len()).any(|at| alternatives.iter().any(|alt| matches_at(&chars, at, alt)))
}

#[cfg(test)]
pub(crate) mod text_probe_tests {
    //! Replays `tests/fixtures/text-probes.json` -- Python 3.13's own results on the acceptance set,
    //! written by `parity/text_semantics.py` -- against the pinned helpers.

    use super::{py_lower, py_re_search, py_split, py_strip, re_alternatives, ReTok};

    pub(crate) fn probes() -> serde_json::Value {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/text-probes.json");
        serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
    }

    fn cases(v: &serde_json::Value, key: &str) -> Vec<(String, serde_json::Value)> {
        v["probes"][key]
            .as_array()
            .unwrap()
            .iter()
            .map(|p| (p[0].as_str().unwrap().to_string(), p[1].clone()))
            .collect()
    }

    fn check(key: &str, f: impl Fn(&str) -> serde_json::Value) {
        let v = probes();
        let all = cases(&v, key);
        assert!(!all.is_empty(), "{key}: no probes");
        let bad: Vec<String> = all
            .iter()
            .filter(|(input, want)| &f(input) != want)
            .map(|(input, want)| format!("{input:?}: Python {want}, Rust {}", f(input)))
            .collect();
        assert!(
            bad.is_empty(),
            "{key}: {} of {} differ, e.g. {:?}",
            bad.len(),
            all.len(),
            &bad[..bad.len().min(5)]
        );
    }

    fn regex(key: &str) -> impl Fn(&str) -> serde_json::Value {
        let pattern = probes()["header"]["reference_regexes"][key]
            .as_str()
            .unwrap()
            .to_string();
        let alts = re_alternatives(&pattern);
        move |s: &str| {
            let refs: Vec<&[ReTok]> = alts.iter().map(Vec::as_slice).collect();
            serde_json::Value::Bool(py_re_search(s, &refs))
        }
    }

    #[test]
    fn lower_matches_python_including_final_sigma() {
        check("lower", |s| serde_json::Value::String(py_lower(s)));
    }

    #[test]
    fn strip_and_split_match_python() {
        check("strip", |s| {
            serde_json::Value::String(py_strip(s).to_string())
        });
        check("split", |s| serde_json::json!(py_split(s)));
    }

    /// The reference compiles both patterns with `re.I` (and `str` patterns carry `re.U`): 2 | 32.
    /// A pattern with other flags (no `re.I`, or `re.X`) must not be searched by `py_re_search`.
    #[test]
    fn the_reference_regexes_are_case_insensitive_and_nothing_else() {
        let v = probes();
        for key in ["transport", "gst_tcs"] {
            assert_eq!(v["header"]["reference_regex_flags"][key], 34, "{key}");
        }
    }

    /// A lower-case literal folds the same extra characters as its capital (`re.I` is symmetric).
    #[test]
    fn a_lower_case_literal_folds_like_its_capital() {
        for (pattern, text) in [
            ("k", "\u{212a}"),
            ("s", "\u{17f}"),
            ("i", "\u{130}"),
            ("i", "\u{131}"),
        ] {
            let alts = re_alternatives(pattern);
            let refs: Vec<&[ReTok]> = alts.iter().map(Vec::as_slice).collect();
            assert!(py_re_search(text, &refs), "{pattern} / {text:?}");
        }
    }

    /// The generated tables were made against the same toolchain tables the case lists were.
    #[test]
    fn the_text_tables_were_generated_against_this_toolchain() {
        let src = include_str!("text_tables.rs");
        let (a, b, c) = char::UNICODE_VERSION;
        assert!(
            src.contains(&format!("Rust char tables, Unicode {a}.{b}.{c};")),
            "text_tables.rs was generated against other Unicode tables: rerun parity/text_semantics.py"
        );
    }

    #[test]
    fn the_reference_regexes_match_as_python_does() {
        check("transport", regex("transport"));
        check("gst_tcs", regex("gst_tcs"));
    }
}

#[cfg(test)]
mod tests {
    use super::{guid_tail12, py_lower, py_upper, LOWER_UNCHANGED, UPPER_UNCHANGED};

    /// The toolchain tables the exception lists were generated against.
    const GENERATED_AGAINST: (u8, u8, u8) = (17, 0, 0);

    #[test]
    fn the_case_tables_are_the_ones_the_exceptions_were_generated_for() {
        assert_eq!(
            char::UNICODE_VERSION,
            GENERATED_AGAINST,
            "the toolchain's Unicode tables moved: regenerate with parity/case_exceptions.py \
             and parity/text_semantics.py, then update GENERATED_AGAINST"
        );
        // The generator's own counts: a dropped or added entry fails here.
        assert_eq!((UPPER_UNCHANGED.len(), LOWER_UNCHANGED.len()), (55, 55));
        assert_eq!(
            unicode_normalization::UNICODE_VERSION,
            (17, 0, 0),
            "NFC tables moved"
        );
        for list in [&UPPER_UNCHANGED[..], &LOWER_UNCHANGED[..]] {
            assert!(list.windows(2).all(|w| w[0] < w[1]), "sorted and unique");
        }
    }

    #[test]
    fn exceptions_keep_their_character_and_everything_else_maps_as_rust_does() {
        assert_eq!(py_upper("\u{0264}ab\u{A7D3}"), "\u{0264}AB\u{A7D3}");
        assert_eq!(py_lower("\u{A7CB}AB"), "\u{A7CB}ab");
        // An exception in the middle of a word: the text either side is lower-cased once each.
        assert_eq!(py_lower("AB\u{A7CB}CD\u{A7CB}EF"), "ab\u{A7CB}cd\u{A7CB}ef");
        assert_eq!(py_upper("straße"), "STRASSE");
        assert_eq!(py_lower("ΟΔΟΣ"), "οδος"); // final sigma, as Python and Rust both do
        assert_eq!(py_lower("İ"), "i\u{307}");
        // Every listed code point maps to itself; the list is exactly where Rust differs.
        for &cp in &UPPER_UNCHANGED {
            let c = char::from_u32(cp).unwrap();
            assert_eq!(py_upper(&c.to_string()), c.to_string());
            assert_ne!(c.to_uppercase().collect::<String>(), c.to_string());
        }
        for &cp in &LOWER_UNCHANGED {
            let c = char::from_u32(cp).unwrap();
            assert_eq!(py_lower(&c.to_string()), c.to_string());
            assert_ne!(c.to_lowercase().collect::<String>(), c.to_string());
        }
    }

    #[test]
    fn the_guid_tail_counts_characters_not_bytes() {
        assert_eq!(guid_tail12("abc"), "abc");
        assert_eq!(guid_tail12("0123456789abcdef"), "456789abcdef");
        // Python: "é".join(...)[-12:] -- 12 characters, 13 bytes here.
        assert_eq!(guid_tail12("xxé0123456789a"), "é0123456789a");
        assert_eq!(guid_tail12("ééééééééééééé"), "éééééééééééé");
        assert_eq!(guid_tail12(""), "");
    }
}
