// SPDX-License-Identifier: Apache-2.0
//! Helpers shared by the test modules ported from batch 1 onward: the reference's voucher
//! evidence label, the tag -> ledger lookup the module invariants resolve figures through, and
//! checked counts and sums.

use std::collections::HashMap;

use crate::book::{Book, Voucher};
use crate::error::{AuditError, Result};
use crate::findings::Value;
use crate::ledger_ids::stable_ledger_tag;
use crate::read::iso;

/// The last 12 characters of a GUID, as the reference's `guid[-12:]` takes them: characters, not
/// bytes, so a non-ASCII GUID neither panics nor gives a different label.
pub(crate) fn guid_tail12(guid: &str) -> &str {
    let chars = guid.chars().count();
    let cut = guid
        .char_indices()
        .nth(chars.saturating_sub(12))
        .map_or(guid.len(), |(i, _)| i);
    &guid[cut..]
}

/// The reference's voucher evidence label: `"<type> <number> on <date>"`, with the GUID's last 12
/// characters standing in for a missing number.
pub(crate) fn voucher_label(v: &Voucher) -> String {
    let num = if v.number.is_empty() {
        guid_tail12(&v.guid)
    } else {
        v.number.as_str()
    };
    format!("{} {} on {}", v.vtype, num, iso(&v.date))
}

/// Every ledger by its stable tag, for resolving a `<figure>_<tag>` id back to its ledger. If two
/// ledgers ever shared a tag, this keeps the last in name order, where the reference's dict keeps
/// the last in read order -- not reachable while tags are unique.
pub(crate) fn ledgers_by_tag(book: &Book) -> Result<HashMap<String, &String>> {
    let mut out = HashMap::new();
    for name in book.ledgers.keys() {
        out.insert(stable_ledger_tag(book, name)?, name);
    }
    Ok(out)
}

/// The error every checked total in a test module raises on i64 overflow.
pub(crate) fn overflow(test_id: &str) -> AuditError {
    AuditError::Config(format!("{test_id}: a total overflowed i64 paise"))
}

/// A count as a figure value.
pub(crate) fn count(test_id: &str, n: usize) -> Result<Value> {
    Ok(Value::Int(i64::try_from(n).map_err(|_| overflow(test_id))?))
}

// The reference's case mapping is Python 3.13's (`unicodedata.unidata_version` 15.1.0); see
// `docs/tax-audit/parity-spec-v1.md`. The two lists below were generated by
// `parity/case_exceptions.py` against the Unicode tables of the pinned toolchain (17.0.0); a
// toolchain with other tables fails `the_case_tables_are_the_ones_the_exceptions_were_generated_for`
// until they are regenerated.

/// Code points whose `to_uppercase` under the pinned toolchain's tables differs from Python 3.13's
/// `str.upper()`; Python maps every one of them to itself.
const UPPER_UNCHANGED: [u32; 55] = [
    0x019B, 0x0264, 0x1C8A, 0xA7CD, 0xA7CF, 0xA7D3, 0xA7D5, 0xA7DB, 0x10D70, 0x10D71, 0x10D72,
    0x10D73, 0x10D74, 0x10D75, 0x10D76, 0x10D77, 0x10D78, 0x10D79, 0x10D7A, 0x10D7B, 0x10D7C,
    0x10D7D, 0x10D7E, 0x10D7F, 0x10D80, 0x10D81, 0x10D82, 0x10D83, 0x10D84, 0x10D85, 0x16EBB,
    0x16EBC, 0x16EBD, 0x16EBE, 0x16EBF, 0x16EC0, 0x16EC1, 0x16EC2, 0x16EC3, 0x16EC4, 0x16EC5,
    0x16EC6, 0x16EC7, 0x16EC8, 0x16EC9, 0x16ECA, 0x16ECB, 0x16ECC, 0x16ECD, 0x16ECE, 0x16ECF,
    0x16ED0, 0x16ED1, 0x16ED2, 0x16ED3,
];

/// The same for `to_lowercase` against `str.lower()`.
const LOWER_UNCHANGED: [u32; 55] = [
    0x1C89, 0xA7CB, 0xA7CC, 0xA7CE, 0xA7D2, 0xA7D4, 0xA7DA, 0xA7DC, 0x10D50, 0x10D51, 0x10D52,
    0x10D53, 0x10D54, 0x10D55, 0x10D56, 0x10D57, 0x10D58, 0x10D59, 0x10D5A, 0x10D5B, 0x10D5C,
    0x10D5D, 0x10D5E, 0x10D5F, 0x10D60, 0x10D61, 0x10D62, 0x10D63, 0x10D64, 0x10D65, 0x16EA0,
    0x16EA1, 0x16EA2, 0x16EA3, 0x16EA4, 0x16EA5, 0x16EA6, 0x16EA7, 0x16EA8, 0x16EA9, 0x16EAA,
    0x16EAB, 0x16EAC, 0x16EAD, 0x16EAE, 0x16EAF, 0x16EB0, 0x16EB1, 0x16EB2, 0x16EB3, 0x16EB4,
    0x16EB5, 0x16EB6, 0x16EB7, 0x16EB8,
];

/// Python 3.13's `str.isspace()` for one character: Rust's `char::is_whitespace` plus
/// U+001C..=U+001F, which Python counts as whitespace and Rust does not (measured over every code
/// point: the only difference).
pub(crate) fn py_isspace(c: char) -> bool {
    c.is_whitespace() || ('\u{1c}'..='\u{1f}').contains(&c)
}

/// Python 3.13's `str.strip()` with no argument.
pub(crate) fn py_strip(text: &str) -> &str {
    text.trim_matches(py_isspace)
}

/// Python 3.13's `str.upper()`: full Unicode case mapping, pinned to Unicode 15.1.0.
pub(crate) fn py_upper(text: &str) -> String {
    text.chars()
        .flat_map(|c| {
            let keep = UPPER_UNCHANGED.binary_search(&u32::from(c)).is_ok();
            let mapped: Vec<char> = if keep {
                vec![c]
            } else {
                c.to_uppercase().collect()
            };
            mapped
        })
        .collect()
}

/// Python 3.13's `str.lower()`, pinned per code point the same way. Exact for every single code
/// point; NOT exact for every string: the final-sigma rule (capital sigma at the end of a word
/// lowers to U+03C2) depends on the Cased and Case_Ignorable properties, which also changed between
/// Unicode 15.1 and 17.0, and those are not pinned here (an independent review measured 52-141
/// differing strings per context, e.g. a sigma after U+0295). Today it lower-cases GUIDs, where a
/// sigma cannot occur in a real read, and `applicability_44ab`'s entity type, where one is not
/// expected but nothing enforces that; a caller lower-casing names needs the text-semantics helpers
/// that pin the rule. The whole string is mapped where no exception applies, so the rule is at
/// least applied on the toolchain's properties.
pub(crate) fn py_lower(text: &str) -> String {
    if !text
        .chars()
        .any(|c| LOWER_UNCHANGED.binary_search(&u32::from(c)).is_ok())
    {
        return text.to_lowercase();
    }
    let mut out = String::with_capacity(text.len());
    let mut run = String::new();
    for c in text.chars() {
        if LOWER_UNCHANGED.binary_search(&u32::from(c)).is_ok() {
            out.push_str(&run.to_lowercase());
            run.clear();
            out.push(c);
        } else {
            run.push(c);
        }
    }
    out.push_str(&run.to_lowercase());
    out
}

#[cfg(test)]
mod tests {
    use super::{guid_tail12, py_lower, py_upper, LOWER_UNCHANGED, UPPER_UNCHANGED};

    /// The toolchain tables the exception lists were generated against.
    const GENERATED_AGAINST: (u8, u8, u8) = (17, 0, 0);

    #[test]
    fn the_case_tables_are_the_ones_the_exceptions_were_generated_for() {
        assert_eq!(
            char::UNICODE_VERSION,
            GENERATED_AGAINST,
            "the toolchain's Unicode tables moved: regenerate the exception lists with \
             parity/case_exceptions.py and update GENERATED_AGAINST"
        );
        // The generator's own counts: a dropped or added entry fails here.
        assert_eq!((UPPER_UNCHANGED.len(), LOWER_UNCHANGED.len()), (55, 55));
        assert_eq!(
            unicode_normalization::UNICODE_VERSION,
            (17, 0, 0),
            "NFC tables moved"
        );
        for list in [&UPPER_UNCHANGED[..], &LOWER_UNCHANGED[..]] {
            assert!(list.windows(2).all(|w| w[0] < w[1]), "sorted and unique");
        }
    }

    #[test]
    fn exceptions_keep_their_character_and_everything_else_maps_as_rust_does() {
        assert_eq!(py_upper("\u{0264}ab\u{A7D3}"), "\u{0264}AB\u{A7D3}");
        assert_eq!(py_lower("\u{A7CB}AB"), "\u{A7CB}ab");
        // An exception in the middle of a word: the text either side is lower-cased once each.
        assert_eq!(py_lower("AB\u{A7CB}CD\u{A7CB}EF"), "ab\u{A7CB}cd\u{A7CB}ef");
        assert_eq!(py_upper("straße"), "STRASSE");
        assert_eq!(py_lower("ΟΔΟΣ"), "οδος"); // final sigma, as Python and Rust both do
        assert_eq!(py_lower("İ"), "i\u{307}");
        // Every listed code point maps to itself; the list is exactly where Rust differs.
        for &cp in &UPPER_UNCHANGED {
            let c = char::from_u32(cp).unwrap();
            assert_eq!(py_upper(&c.to_string()), c.to_string());
            assert_ne!(c.to_uppercase().collect::<String>(), c.to_string());
        }
        for &cp in &LOWER_UNCHANGED {
            let c = char::from_u32(cp).unwrap();
            assert_eq!(py_lower(&c.to_string()), c.to_string());
            assert_ne!(c.to_lowercase().collect::<String>(), c.to_string());
        }
    }

    #[test]
    fn the_guid_tail_counts_characters_not_bytes() {
        assert_eq!(guid_tail12("abc"), "abc");
        assert_eq!(guid_tail12("0123456789abcdef"), "456789abcdef");
        // Python: "é".join(...)[-12:] -- 12 characters, 13 bytes here.
        assert_eq!(guid_tail12("xxé0123456789a"), "é0123456789a");
        assert_eq!(guid_tail12("ééééééééééééé"), "éééééééééééé");
        assert_eq!(guid_tail12(""), "");
    }
}
