# SPDX-License-Identifier: Apache-2.0
"""Generate `src/text_tables.rs` and `tests/fixtures/text-probes.json` from Python 3.13, the
reference implementation's runtime, against this toolchain's own tables.

    cargo run --locked --release -p bridge-tax-audit --example text_semantics_dump > /tmp/dump.tsv
    uv run -q --python 3.13 python parity/text_semantics.py ENGINE /tmp/dump.tsv

ENGINE is the reference implementation's engine directory (its regular expressions are read from
the modules, not copied). Measured over every code point, it refuses unless:
- Python's `\\w` is exactly `isalnum() or "_"`;
- Python's alphanumerics are a subset of Rust's `is_alphanumeric` (so a range list of the
  difference is enough);
- Python's whitespace is Rust's plus U+001C..U+001F.
It writes:
- the ranges where Rust says alphanumeric and Python does not;
- the extra characters `re.I` matches for each ASCII letter;
- Python's effective Cased and Case_Ignorable sets for the final-sigma rule, found by probing
  `str.lower()` itself;
- the non-ASCII code points Python's `\\d` matches, measured over every code point, for the
  quantity and rate readers in `src/book.rs`;
- the probe file: Python's own results on the acceptance set (Latin, Latin-1/Ext-A/B, modifier
  letters and combining diacriticals, currency symbols, Devanagari
  and the other Indic scripts, general punctuation, NBSP and the whitespace Tally emits), which
  `src/support.rs`'s `text_probe_tests` replay in CI. After writing, run
`cargo fmt -p bridge-tax-audit`: the tables are emitted unwrapped.
"""
from __future__ import annotations

import importlib
import json
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SIGMA = "Σ"


def ranges(cps):
    out = []
    for cp in cps:
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def rust_ranges(name, rs):
    body = "\n".join("    (0x{:04X}, 0x{:04X}),".format(a, b) for a, b in rs)
    return f"pub(crate) const {name}: [(u32, u32); {len(rs)}] = [\n{body}\n];\n"


def acceptance():
    cps = list(range(0x20, 0x250)) + list(range(0x02B0, 0x0370)) + list(range(0x0900, 0x0E00))
    cps += list(range(0x2000, 0x2070)) + list(range(0x20A0, 0x20D0))
    cps += [0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x1C, 0x1D, 0x1E, 0x1F, 0xA0, 0x202F, 0xFEFF, 0x3000]
    return sorted({cp for cp in cps if unicodedata.category(chr(cp)) != "Cn"})


def main() -> int:
    engine, dump = Path(sys.argv[1]).resolve(), Path(sys.argv[2])
    sys.path.insert(0, str(engine))
    transport = importlib.import_module("tae.audit_tests.cash_payments_40a3").TRANSPORT_NAME_RE
    gst_tcs = importlib.import_module("tae.audit_tests.depreciation").GST_TCS_RE
    lines = dump.read_text(encoding="utf-8").splitlines()
    rust_version, rows = lines[0], [l.split("\t") for l in lines[1:]]
    word = re.compile(r"\w")
    not_alnum, extra_space = [], []
    for cp_hex, alnum, space, _up, _lo in rows:
        cp = int(cp_hex, 16)
        c = chr(cp)
        if bool(word.fullmatch(c)) != (c.isalnum() or c == "_"):
            raise SystemExit(f"U+{cp:04X}: Python \\w is not isalnum-or-underscore")
        if c.isalnum() and alnum != "1":
            raise SystemExit(f"U+{cp:04X}: Python alphanumeric, Rust not; a range list is not enough")
        if alnum == "1" and not c.isalnum():
            not_alnum.append(cp)
        if c.isspace() != (space == "1"):
            extra_space.append(cp)
    if extra_space != [0x1C, 0x1D, 0x1E, 0x1F]:
        raise SystemExit(f"whitespace differs beyond U+001C..U+001F: {extra_space}")
    ci = {}
    for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
        pat = re.compile(letter, re.I)
        ci[letter] = [int(r[0], 16) for r in rows if int(r[0], 16) >= 0x80 and pat.fullmatch(chr(int(r[0], 16)))]
    cased, ignorable = [], []
    for r in rows:
        c = chr(int(r[0], 16))
        a = (c + SIGMA).lower()[-1] == "ς"
        b = ("Α" + c + SIGMA).lower()[-1] == "ς"
        if a:
            cased.append(ord(c))
        elif b:
            ignorable.append(ord(c))
    digit = re.compile(r"\d")
    decimals = [cp for cp in range(0x80, 0x110000) if digit.fullmatch(chr(cp))]
    ci_rows = "\n".join(f"    ('{l}', &[{', '.join(f'0x{c:04X}' for c in cs)}])," for l, cs in ci.items() if cs)
    out = (
        "// SPDX-License-Identifier: Apache-2.0\n"
        "// GENERATED by parity/text_semantics.py -- do not edit.\n"
        f"// {rust_version}; Python {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}.\n\n"
        "//! Python 3.13's text semantics as tables against this toolchain's own (`support.rs` uses them).\n\n"
        "/// Code points Rust's `is_alphanumeric` accepts and Python's `str.isalnum` does not.\n"
        + rust_ranges("NOT_PY_ALNUM", ranges(not_alnum))
        + "\n/// Non-ASCII code points Python's `re.I` matches to each ASCII letter (every other letter\n"
        "/// matches only its own two cases).\n"
        f"pub(crate) const PY_CI_EXTRA: [(char, &[u32]); {sum(1 for cs in ci.values() if cs)}] = [\n{ci_rows}\n];\n"
        "\n/// Python's effective Cased set for the final-sigma rule: a character after which a capital\n"
        "/// sigma lowers to the final form.\n"
        + rust_ranges("PY_CASED", ranges(cased))
        + "\n/// Python's effective Case_Ignorable set for the final-sigma rule (skipped when looking for a\n"
        "/// cased neighbour). It includes characters that are also Cased (U+0345, modifier letters):\n"
        "/// CPython skips them before asking whether they are cased, so here they are ignorable only.\n"
        + rust_ranges("PY_CASE_IGNORABLE", ranges(ignorable))
        + "\n/// Non-ASCII code points Python's `\\d` matches: its decimal digits, which `re` and `float()`\n"
        "/// read as numbers where this crate's readers take ASCII only (`book.rs` refuses text holding\n"
        "/// one).\n"
        + rust_ranges("PY_DECIMAL_NON_ASCII", ranges(decimals))
    )
    (ROOT / "src" / "text_tables.rs").write_text(out, encoding="utf-8")

    acc = acceptance()
    probes = {"lower": [], "strip": [], "split": [], "transport": [], "gst_tcs": []}
    for cp in acc:
        c = chr(cp)
        for s in ("Α" + c + SIGMA, "Α" + SIGMA + c, c + SIGMA, "Α" + SIGMA + c + "Β",
                  "AB" + c + "CD"):
            probes["lower"].append([s, s.lower()])
        for s in (c + "ab" + c, " x" + c + "y "):
            probes["strip"].append([s, s.strip()])
        probes["split"].append(["a" + c + "b  c", ("a" + c + "b  c").split()])
        for s in (c + "GST", "GST" + c, "C" + c + "GST", "cgst" + c, c + "tcs" + c):
            probes["gst_tcs"].append([s, bool(gst_tcs.search(s))])
        for s in ("ROAD" + c + "LINES", "LOG" + c + "STIC", c + "Cargo", "FRE" + c + "GHT", "RO" + c + "DWAYS"):
            probes["transport"].append([s, bool(transport.search(s))])
    for s in ("İLOG", "LOGİSTIC", "CARRıER", "LOﬆIC", "STRAßE CARGO", "ROAD\x1cLINES",
              "roadlines", "Invented Road Lines", "invented logistic", "ABC LOGISTICS"):
        probes["transport"].append([s, bool(transport.search(s))])
    for s in ("CGST INPUT", "cgst input", "Input Igst", "Gstin Register", "ABCGST", "कGST", "GSTा"):
        probes["gst_tcs"].append([s, bool(gst_tcs.search(s))])
    header = {"generated_by": "parity/text_semantics.py", "python": sys.version.split()[0],
              "unicode": unicodedata.unidata_version, "reference_regexes": {"transport": transport.pattern,
              "gst_tcs": gst_tcs.pattern}, "reference_regex_flags": {"transport": transport.flags,
              "gst_tcs": gst_tcs.flags}}
    (ROOT / "tests" / "fixtures" / "text-probes.json").write_text(
        json.dumps({"header": header, "probes": probes}, ensure_ascii=False, indent=0) + "\n", encoding="utf-8")
    print(f"NOT_PY_ALNUM {len(ranges(not_alnum))} ranges; PY_CASED {len(ranges(cased))}; "
          f"PY_CASE_IGNORABLE {len(ranges(ignorable))}; ci extras {{{', '.join(f'{l}: {len(cs)}' for l, cs in ci.items() if cs)}}}; "
          f"probes {', '.join(f'{k}={len(v)}' for k, v in probes.items())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
