#!/usr/bin/env node
import { access, cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { assertNoTestSeam } from "./check-no-test-seam.mjs";
import { arch, platform } from "node:os";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = resolve(import.meta.dirname, "..");
const requiredResources = [
  "LICENSE",
  "NOTICE",
  "THIRD_PARTY_LICENSES.txt",
  "THIRD_PARTY_LICENSES_RUST.txt",
];
// PDFium sits beside the MCP binary, which is where `parse_bank_statement`
// loads it from; its licence notice is generated by scripts/fetch-pdfium.py
// from the pinned archive and staged at the bundle root.
export const pdfiumNotice = "THIRD_PARTY_LICENSES_PDFIUM.txt";
const hostTargets = {
  "darwin-arm64": { target: "aarch64-apple-darwin", binary: "bridge_mcp", pdfium: "libpdfium.dylib" },
  "darwin-x64": { target: "x86_64-apple-darwin", binary: "bridge_mcp", pdfium: "libpdfium.dylib" },
  "win32-x64": { target: "x86_64-pc-windows-msvc", binary: "bridge_mcp.exe", pdfium: "pdfium.dll" },
};

export function mcpbHostTarget(hostPlatform = platform(), hostArch = arch()) {
  const key = `${hostPlatform}-${hostArch}`;
  const target = hostTargets[key];
  if (!target) throw new Error(`MCPB staging does not support host ${key}`);
  return { key, ...target };
}

export async function verifyMcpbStage(stageDirectory) {
  const missing = [];
  for (const resource of requiredResources) {
    try {
      await access(resolve(stageDirectory, resource));
    } catch {
      missing.push(resource);
    }
  }
  if (missing.length > 0) {
    throw new Error(`MCPB stage missing required license resources: ${missing.join(", ")}`);
  }
  let manifest;
  try {
    manifest = JSON.parse(await readFile(resolve(stageDirectory, "manifest.json"), "utf8"));
  } catch {
    throw new Error("MCPB stage manifest is missing or invalid");
  }
  const binary = manifest.server?.entry_point;
  const host = Object.values(hostTargets).find(
    (candidate) => binary === `bin/${candidate.target}/${candidate.binary}`,
  );
  if (!host) {
    throw new Error("MCPB stage manifest has no supported host binary entry point");
  }
  const expectedPlatform = host.target.includes("windows") ? "win32" : "darwin";
  if (JSON.stringify(manifest.compatibility?.platforms) !== JSON.stringify([expectedPlatform])) {
    throw new Error("MCPB stage must advertise only its binary's operating system");
  }
  if (manifest.server.mcp_config?.command !== `\${__dirname}/${binary}`) {
    throw new Error("MCPB launch command does not match its staged binary");
  }
  try {
    await access(resolve(stageDirectory, binary));
  } catch {
    throw new Error(`MCPB stage is missing binary ${binary}`);
  }
  const library = `bin/${host.target}/${host.pdfium}`;
  for (const [path, label] of [[library, "PDFium library"], [pdfiumNotice, "PDFium licence notice"]]) {
    try {
      await access(resolve(stageDirectory, path));
    } catch {
      throw new Error(`MCPB stage is missing the ${label} ${path}`);
    }
  }
}

export async function stagePdfium(stageDirectory, pdfiumDirectory, host = mcpbHostTarget()) {
  const library = `bin/${host.target}/${host.pdfium}`;
  await mkdir(resolve(stageDirectory, "bin", host.target), { recursive: true });
  await cp(resolve(pdfiumDirectory, host.pdfium), resolve(stageDirectory, library));
  await cp(resolve(pdfiumDirectory, pdfiumNotice), resolve(stageDirectory, pdfiumNotice));
  return library;
}

export async function stageMcpbResources(stageDirectory, sourceRoot = root) {
  for (const resource of requiredResources) {
    await cp(resolve(sourceRoot, resource), resolve(stageDirectory, resource));
  }
}

export async function stageHostManifest(stageDirectory, sourceRoot = root, host = mcpbHostTarget()) {
  const template = JSON.parse(
    await readFile(resolve(sourceRoot, "packaging", "mcpb", "manifest.json"), "utf8"),
  );
  const entryPoint = `bin/${host.target}/${host.binary}`;
  template.server.entry_point = entryPoint;
  template.server.mcp_config.command = `\${__dirname}/${entryPoint}`;
  template.compatibility = { platforms: [host.key.split("-")[0]] };
  await mkdir(stageDirectory, { recursive: true });
  await writeFile(resolve(stageDirectory, "manifest.json"), `${JSON.stringify(template, null, 2)}\n`);
  return entryPoint;
}

export function releaseMcpbBinaryPath(sourceRoot = root, binary) {
  return resolve(sourceRoot, "src-tauri", "target", "release", binary);
}

const usage =
  "usage: node scripts/package-mcpb.mjs --pdfium /dir/from/fetch-pdfium [--binary /path/to/bridge_mcp]";

export function packageMcpbArguments(argumentsList) {
  const parsed = { binaryPath: undefined, pdfiumDirectory: undefined };
  const keys = { "--binary": "binaryPath", "--pdfium": "pdfiumDirectory" };
  for (let index = 0; index < argumentsList.length; index += 2) {
    const key = keys[argumentsList[index]];
    const value = argumentsList[index + 1];
    if (!key || !value || parsed[key] !== undefined) throw new Error(usage);
    parsed[key] = resolve(value);
  }
  // A bundle without PDFium would list parse_bank_statement and fail every call.
  if (parsed.pdfiumDirectory === undefined) throw new Error(usage);
  return parsed;
}

async function main() {
  const { binaryPath, pdfiumDirectory } = packageMcpbArguments(process.argv.slice(2));
  const host = mcpbHostTarget();
  const sourceBinary = binaryPath ?? releaseMcpbBinaryPath(root, host.binary);
  if (!binaryPath) {
    const manifest = resolve(root, "src-tauri", "Cargo.toml");
    const build = spawnSync("cargo", ["build", "--locked", "--release", "--manifest-path", manifest, "--bin", "bridge_mcp"], {
      cwd: root,
      stdio: "inherit",
    });
    if (build.status !== 0) process.exit(build.status ?? 1);
  }
  try {
    await access(sourceBinary);
  } catch {
    throw new Error(`MCPB binary is missing: ${sourceBinary}`);
  }
  // Every MCPB, from CI, a release or a local build, is staged here: refuse a
  // binary compiled with the test-only approval seam (bridge#583).
  assertNoTestSeam([sourceBinary]);

  const stageDirectory = resolve(root, "packaging", "mcpb", "stage");
  await rm(stageDirectory, { recursive: true, force: true });
  const entryPoint = await stageHostManifest(stageDirectory, root, host);
  const destination = resolve(stageDirectory, entryPoint);
  await mkdir(resolve(stageDirectory, "bin", host.target), { recursive: true });
  await cp(sourceBinary, destination);
  await stageMcpbResources(stageDirectory);
  const library = await stagePdfium(stageDirectory, pdfiumDirectory, host);
  await verifyMcpbStage(stageDirectory);
  console.log(`Prepared ${destination} from ${sourceBinary}, staged ${library} from ${pdfiumDirectory}, and verified the ${host.key} binary, PDFium library, launch manifest, and legal resources; do not commit host artifacts.`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
