//! Desktop Journal review capability, native selection, and thin operation orchestration.
use super::desktop_journal::{DesktopJournalOperation, DesktopJournalService};
use super::*;
use crate::tally::{TallyConfig, TallyRuntime};
use serde::{Deserialize, Serialize};
use std::io::Read;

const MAX_SELECTED_JOURNAL_BYTES: usize = 5_000_000;

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct DesktopJournalCompany {
    pub(crate) name: String,
    pub(crate) guid: String,
    pub(crate) company_number: String,
    pub(crate) books_from: String,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct DesktopJournalEntry {
    pub(crate) ledger: String,
    pub(crate) side: String,
    pub(crate) amount: String,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct DesktopJournalDetails {
    pub(crate) date: String,
    pub(crate) reference: Option<String>,
    pub(crate) narration: Option<String>,
    pub(crate) entries: Vec<DesktopJournalEntry>,
    pub(crate) total_debit: String,
    pub(crate) total_credit: String,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DesktopJournalReview {
    pub(crate) batch_id: String,
    pub(crate) sha256: String,
    pub(crate) company: DesktopJournalCompany,
    pub(crate) built_at: String,
    pub(crate) dispatched: bool,
    pub(crate) response_recorded: bool,
    pub(crate) details: DesktopJournalDetails,
}

#[derive(Debug)]
pub(crate) struct DesktopJournalError {
    pub(crate) code: &'static str,
    pub(crate) message: String,
    pub(crate) remediation: &'static str,
}

impl DesktopJournalError {
    fn refused(code: impl AsRef<str>) -> Self {
        let (message, remediation) = match code.as_ref() {
            "import_selected_file_not_found" | "import_persisted_file_unavailable" => (
                "This file was not generated by Bridge on this computer, or its saved batch is unavailable.",
                "Choose the original file from the Bridge installation that built it. A Journal XML alone is not portable between computers.",
            ),
            "import_selected_file_not_exact" | "import_batch_changed" => (
                "This file no longer matches its original saved Bridge Journal.",
                "Choose the unchanged original file again. Do not edit or rebuild it to retry.",
            ),
            "import_post_endpoint_mismatch" => (
                "This saved Journal was built for a different Tally endpoint.",
                "Reconnect to the saved host and port, then choose the original Journal again.",
            ),
            "import_selected_file_too_large"
            | "import_persisted_file_too_large"
            | "import_review_too_large" => (
                "This Journal is too large for Bridge's one-Journal desktop review.",
                "Use the manual workflow for this file; Bridge will not truncate the review.",
            ),
            "file_picker_failed" => (
                "Bridge could not open the native file picker.",
                "Close any modal dialogs and choose the Journal file again.",
            ),
            _ => (
                "Bridge could not open this saved Journal for review.",
                "Choose only the original Bridge-generated Journal file and keep its saved batch unchanged.",
            ),
        };
        Self {
            code: "journal_review_refused",
            message: message.into(),
            remediation,
        }
    }
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DesktopJournalDescriptorRequest {
    pub(crate) batch_id: String,
    pub(crate) sha256: String,
    pub(crate) company_guid: String,
    pub(crate) config: TallyConfig,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DesktopJournalActionResponse {
    pub(crate) batch_id: String,
    pub(crate) result: Value,
}

fn action(batch_id: String, operation: DesktopJournalOperation) -> DesktopJournalActionResponse {
    DesktopJournalActionResponse {
        batch_id,
        result: operation.result,
    }
}

pub(crate) async fn pick_for_review(
    config: TallyConfig,
    runtime: TallyRuntime,
) -> Result<Option<DesktopJournalReview>, DesktopJournalError> {
    let selected = tokio::task::spawn_blocking(|| {
        let Some(path) = rfd::FileDialog::new()
            .set_title("Select a Bridge Journal")
            .add_filter("Bridge Journal", &["xml"])
            .pick_file()
        else {
            return Ok(None);
        };
        let mut file = super::super::local_file::open_local_file(&path, false)
            .map_err(|_| "import_selected_file_unavailable".to_string())?;
        let length = file
            .metadata()
            .map_err(|_| "import_selected_file_unavailable".to_string())?
            .len();
        if length > MAX_SELECTED_JOURNAL_BYTES as u64 {
            return Err("import_selected_file_too_large".to_string());
        }
        let mut bytes = Vec::with_capacity(length as usize);
        std::io::Read::by_ref(&mut file)
            .take((MAX_SELECTED_JOURNAL_BYTES + 1) as u64)
            .read_to_end(&mut bytes)
            .map_err(|_| "import_selected_file_unavailable".to_string())?;
        if bytes.len() > MAX_SELECTED_JOURNAL_BYTES {
            return Err("import_selected_file_too_large".to_string());
        }
        Ok(Some(bytes))
    })
    .await
    .map_err(|_| DesktopJournalError::refused("file_picker_failed"))?
    .map_err(DesktopJournalError::refused)?;
    let Some(selected) = selected else {
        return Ok(None);
    };
    let service =
        DesktopJournalService::new(config, runtime).map_err(DesktopJournalError::refused)?;
    let review = service
        .review_selected_xml(&selected)
        .map_err(DesktopJournalError::refused)?;
    Ok(Some(review))
}

pub(crate) async fn post_reviewed(
    request: DesktopJournalDescriptorRequest,
    runtime: TallyRuntime,
) -> Result<DesktopJournalActionResponse, DesktopJournalError> {
    let service = DesktopJournalService::new(request.config, runtime)
        .map_err(DesktopJournalError::refused)?;
    let operation = service
        .post(&request.batch_id, &request.sha256, &request.company_guid)
        .await
        .map_err(DesktopJournalError::refused)?;
    Ok(action(request.batch_id, operation))
}

pub(crate) async fn reconcile_reviewed(
    request: DesktopJournalDescriptorRequest,
    runtime: TallyRuntime,
) -> Result<DesktopJournalActionResponse, DesktopJournalError> {
    let service = DesktopJournalService::new(request.config, runtime)
        .map_err(DesktopJournalError::refused)?;
    let operation = service
        .reconcile(&request.batch_id, &request.sha256, &request.company_guid)
        .await
        .map_err(DesktopJournalError::refused)?;
    Ok(action(request.batch_id, operation))
}
